steps:
    - name: gcr.io/cloud-builders/gcloud
      id: 'DEPLOY FUNCTIONS'
      args:
          [
              "functions",
              "deploy",
              "${_NAME}",
              "--runtime=python37",
              "--region=${_REGION}",
              "--memory=${_MEMORY}",
              "--trigger-topic=${_TOPIC}",
              "--entry-point=handle_build",
              "--project=${_PROJECT_ID}",
              "--set-env-vars=TOKEN_V2=${_TOKEN_V2},NOTION_LINK=${_NOTION_LINK},API_KEY=${_API_KEY},USR=${_USR},PSW=${_PSW}"
          ]
